// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaultConnection.Data;

#nullable disable

namespace VaultConnection.Migrations
{
    [DbContext(typeof(VaultConnectionDbContext))]
    [Migration("20260707074020_UpdateDeleteBehavior")]
    partial class UpdateDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VaultConnection.Models.SharePointListDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ListId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ListTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SharePointSiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SharePointSiteId", "ListId")
                        .IsUnique();

                    b.ToTable("SharePointListDetails", (string)null);
                });

            modelBuilder.Entity("VaultConnection.Models.SharePointSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SharePointSites", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SiteTitle = "The Organization Perspective",
                            SiteUrl = "https://mso365e5.sharepoint.com/sites/ThePerspective"
                        },
                        new
                        {
                            Id = 2,
                            SiteTitle = "Sample SharePoint Site",
                            SiteUrl = "https://mso365e5.sharepoint.com/sites/SampleSharePointSite"
                        });
                });

            modelBuilder.Entity("VaultConnection.Models.SharePointListDetail", b =>
                {
                    b.HasOne("VaultConnection.Models.SharePointSite", "SharePointSite")
                        .WithMany("ListDetails")
                        .HasForeignKey("SharePointSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SharePointSite");
                });

            modelBuilder.Entity("VaultConnection.Models.SharePointSite", b =>
                {
                    b.Navigation("ListDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
